name: Docker

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    environment:
      name: Development

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: sruthimallela447
          password: 5af88563-3519-420d-ba35-e1e386f7a96c
      
      - name: Build image
        run: |
          docker images
          docker build . --file Api/Dockerfile.original --tag api
          docker images 
          
      - name: Push image
        run: |
          docker tag $(docker images -q --format='{{.ID}}' | head -1) sruthimallela447/api
          docker push sruthimallela447/api
